package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/blackbeardONE/QSDM/pkg/chain"
	"github.com/blackbeardONE/QSDM/pkg/mempool"
)

// The scanner reads a chain file. If it misreads the format it reports zero
// task actions and an operator concludes the chain is clean -- then sets an
// activation height that rejects real transactions and stops the node
// following the chain. A silent zero is the dangerous answer here, not an
// error.
//
// The first version of this test hand-wrote the fixture JSON and produced
// exactly that false zero, because ContractID carries a json tag
// (`contract_id`) while its neighbours do not. The fixture is now generated by
// marshalling the real types, so it cannot drift from what a node writes.
func writeFixture(t *testing.T, path string, blocks []*chain.Block) {
	t.Helper()
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("create fixture: %v", err)
	}
	defer f.Close()
	for _, b := range blocks {
		line, err := json.Marshal(b)
		if err != nil {
			t.Fatalf("marshal block: %v", err)
		}
		if _, err := f.Write(append(line, '\n')); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
	}
}

func TestScan_CountsTaskActionsAndFindsTheLastUnsigned(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{
		{Height: 0},
		{Height: 1, Transactions: []*mempool.Tx{
			{ID: "signed", ContractID: chain.TaskContractID, Signature: "a", PublicKey: "b"},
		}},
		{Height: 2, Transactions: []*mempool.Tx{
			{ID: "unsigned", ContractID: chain.TaskContractID},
		}},
		{Height: 3, Transactions: []*mempool.Tx{
			{ID: "unrelated", ContractID: chain.WalletTransferContractID},
		}},
	})

	got, err := scanChain(path)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if got.blocks != 4 {
		t.Errorf("blocks = %d, want 4", got.blocks)
	}
	if got.tipHeight != 3 {
		t.Errorf("tip = %d, want 3", got.tipHeight)
	}
	if got.taskActions != 2 {
		t.Errorf("task actions = %d, want 2 -- a wrong count here sends an operator "+
			"to a bad activation height", got.taskActions)
	}
	if got.unsigned != 1 {
		t.Errorf("unsigned = %d, want 1", got.unsigned)
	}
	if !got.haveUnsigned || got.lastUnsignedAt != 2 {
		t.Errorf("last unsigned at = %d (present=%v), want 2 -- this is the number the "+
			"activation height must exceed", got.lastUnsignedAt, got.haveUnsigned)
	}
}

// A chain with no task actions at all must say so, and must not be
// indistinguishable from a chain the scanner failed to parse.
func TestScan_CleanChainReportsNoUnsigned(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{
		{Height: 0},
		{Height: 1, Transactions: []*mempool.Tx{
			{ID: "w", ContractID: chain.WalletTransferContractID},
		}},
	})

	got, err := scanChain(path)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if got.taskActions != 0 || got.unsigned != 0 || got.haveUnsigned {
		t.Errorf("expected a clean chain, got %+v", got)
	}
	if got.blocks != 2 {
		t.Errorf("blocks = %d, want 2 -- if this is 0 the file was not read at all, "+
			"which would look identical to a clean chain in the report", got.blocks)
	}
}

// A malformed line must be an error, not a short count. Silently stopping at a
// bad line would under-report and produce a too-low activation height.
func TestScan_MalformedLineIsAnErrorNotAShortCount(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{{Height: 0}})
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if _, err := f.WriteString("{not valid json\n"); err != nil {
		t.Fatalf("append: %v", err)
	}
	f.Close()

	if _, err := scanChain(path); err == nil {
		t.Error("a malformed chain line must be reported, not silently skipped: " +
			"a short count yields a too-low activation height, which rejects real transactions")
	}
}
