package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/blackbeardONE/QSDM/pkg/chain"
	"github.com/blackbeardONE/QSDM/pkg/mempool"
)

// The scanner reads a chain file. If it misreads the format it reports zero
// task actions and an operator concludes the chain is clean -- then sets an
// activation height that rejects real transactions and stops the node
// following the chain. A silent zero is the dangerous answer here, not an
// error.
//
// The first version of this test hand-wrote the fixture JSON and produced
// exactly that false zero, because ContractID carries a json tag
// (`contract_id`) while its neighbours do not. The fixture is now generated by
// marshalling the real types, so it cannot drift from what a node writes.
func writeFixture(t *testing.T, path string, blocks []*chain.Block) {
	t.Helper()
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("create fixture: %v", err)
	}
	defer f.Close()
	for _, b := range blocks {
		line, err := json.Marshal(b)
		if err != nil {
			t.Fatalf("marshal block: %v", err)
		}
		if _, err := f.Write(append(line, '\n')); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
	}
}

func TestScan_CountsTaskActionsAndFindsTheLastUnsigned(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{
		{Height: 0},
		{Height: 1, Transactions: []*mempool.Tx{
			{ID: "signed", ContractID: chain.TaskContractID, Signature: "a", PublicKey: "b"},
		}},
		{Height: 2, Transactions: []*mempool.Tx{
			{ID: "unsigned", ContractID: chain.TaskContractID},
		}},
		{Height: 3, Transactions: []*mempool.Tx{
			{ID: "unrelated", ContractID: chain.WalletTransferContractID},
		}},
	})

	got, err := scanChain(path)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if got.blocks != 4 {
		t.Errorf("blocks = %d, want 4", got.blocks)
	}
	if got.tipHeight != 3 {
		t.Errorf("tip = %d, want 3", got.tipHeight)
	}
	if got.taskActions != 2 {
		t.Errorf("task actions = %d, want 2 -- a wrong count here sends an operator "+
			"to a bad activation height", got.taskActions)
	}
	if got.unsigned != 1 {
		t.Errorf("unsigned = %d, want 1", got.unsigned)
	}
	if !got.haveUnsigned || got.lastUnsignedAt != 2 {
		t.Errorf("last unsigned at = %d (present=%v), want 2 -- this is the number the "+
			"activation height must exceed", got.lastUnsignedAt, got.haveUnsigned)
	}
}

// A chain with no task actions at all must say so, and must not be
// indistinguishable from a chain the scanner failed to parse.
func TestScan_CleanChainReportsNoUnsigned(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{
		{Height: 0},
		{Height: 1, Transactions: []*mempool.Tx{
			{ID: "w", ContractID: chain.WalletTransferContractID},
		}},
	})

	got, err := scanChain(path)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if got.taskActions != 0 || got.unsigned != 0 || got.haveUnsigned {
		t.Errorf("expected a clean chain, got %+v", got)
	}
	if got.blocks != 2 {
		t.Errorf("blocks = %d, want 2 -- if this is 0 the file was not read at all, "+
			"which would look identical to a clean chain in the report", got.blocks)
	}
}

// A malformed line must be an error, not a short count. Silently stopping at a
// bad line would under-report and produce a too-low activation height.
func TestScan_MalformedLineIsAnErrorNotAShortCount(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{{Height: 0}})
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if _, err := f.WriteString("{not valid json\n"); err != nil {
		t.Fatalf("append: %v", err)
	}
	f.Close()

	if _, err := scanChain(path); err == nil {
		t.Error("a malformed chain line must be reported, not silently skipped: " +
			"a short count yields a too-low activation height, which rejects real transactions")
	}
}

// A chain file we could not read must never yield a suggested height.
//
// This calls run(), NOT scanChain. The first version of this test called
// scanChain and asserted it returned zeros -- which it did before the guard
// existed, so neutering the guard left every test passing and a reviewer
// reproduced the original bug against the neutered binary. The guard is the
// entire point of the change, so the test has to reach it.
func TestRun_RefusesToAdviseOnAnUnreadChain(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "empty.ndjson")
	if err := os.WriteFile(path, nil, 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}

	var out, errOut bytes.Buffer
	code := run(path, 1000, &out, &errOut)

	if code == 0 {
		t.Error("an unread chain must not exit 0: automation would treat it as success")
	}
	if strings.Contains(out.String(), "suggested") {
		t.Errorf("no activation height may be suggested for a chain we did not read; got:\n%s", out.String())
	}
	if !strings.Contains(errOut.String(), "REFUSING TO ADVISE") {
		t.Errorf("the refusal must say why on stderr; got:\n%s", errOut.String())
	}
}

// ...and it must NOT refuse on a legitimate chain, or the guard is just a
// tool that never works.
func TestRun_AdvisesOnARealChain(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{
		{Height: 0},
		{Height: 1, Transactions: []*mempool.Tx{
			{ID: "unsigned", ContractID: chain.TaskContractID},
		}},
	})

	var out, errOut bytes.Buffer
	code := run(path, 100, &out, &errOut)

	if code != 0 {
		t.Fatalf("a real chain must advise, got exit %d, stderr:\n%s", code, errOut.String())
	}
	// tip 1, last unsigned 1, margin 100 -> 101.
	if !strings.Contains(out.String(), "suggested task_action_signature_activation_height = 101") {
		t.Errorf("wrong or missing suggestion:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "would reject them and stop this node") {
		t.Errorf("an existing unsigned action must carry the warning:\n%s", out.String())
	}
}

// Blank lines are legitimate in an NDJSON file and must not be mistaken for an
// unread chain -- otherwise the guard above would fire on a real chain.
func TestScan_BlankLinesAreNotBlocks(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chain.ndjson")
	writeFixture(t, path, []*chain.Block{{Height: 0}, {Height: 1}})
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if _, err := f.WriteString("\n\n   \n"); err != nil {
		t.Fatalf("append: %v", err)
	}
	f.Close()

	got, err := scanChain(path)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if got.blocks != 2 {
		t.Errorf("blocks = %d, want 2: blank lines must not count as blocks, "+
			"nor cause a parse error", got.blocks)
	}
}
