package legacymining

// HL2 WP-A: config v2, the v1 compatibility guarantees, the mode/version
// rules and the fail-closed gate.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// goldenPhase1 is a byte-for-byte copy of the phase-1 style v1 config as
// generated by hl1/make-canary-config.py at HL1 master db1725f
// (hl1/canary/mining-canary.phase1.example.json), with its SHA-256. The
// deployed canary config has this exact shape; only the address, node and
// expiry differ.
const goldenPhase1 = `{
 "version": 1,
 "allowed": [
  {
   "miner_addr": "0000000000000000000000000000000000000000000000000000000000000000",
   "node_id": "EXAMPLE-NODE-ID"
  }
 ],
 "max_proofs_per_min": 60,
 "max_proofs_total": 3000,
 "max_pending": 600,
 "budget_cell": 1291,
 "expires_unix": 1790003600
}
`

const goldenPhase1SHA256 = "18d63aedfd24ae8934be50acffb43fd7dc8aedb6aa2be56a2db495de32b6da9c"

func mustPin(t *testing.T, h string) ConfigHash {
	t.Helper()
	var pin ConfigHash
	if _, err := hex.Decode(pin[:], []byte(h)); err != nil || len(h) != 64 {
		t.Fatalf("pin %q: %v", h, err)
	}
	return pin
}

// The v1 config hash is the SHA-256 of the raw bytes, exactly as in HL1, and
// the golden v1 config still loads to the same Config.
func TestConfigV1GoldenHashUnchanged(t *testing.T) {
	data := []byte(goldenPhase1)
	pin := mustPin(t, goldenPhase1SHA256)
	if sum := sha256.Sum256(data); sum != pin {
		t.Fatalf("golden bytes hash %x, want %s", sum, goldenPhase1SHA256)
	}
	committed, err := os.ReadFile(filepath.Join("..", "..", "..", "hl1", "canary", "mining-canary.phase1.example.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(committed, data) {
		t.Fatal("hl1/canary/mining-canary.phase1.example.json differs from the golden v1 config")
	}
	c, err := ParseConfig(data, pin)
	if err != nil {
		t.Fatalf("golden v1: %v", err)
	}
	want := Config{
		Version:         1,
		Allowed:         []AllowEntry{{MinerAddr: strings.Repeat("0", 64), NodeID: "EXAMPLE-NODE-ID"}},
		MaxProofsPerMin: 60, MaxProofsTotal: 3000, MaxPending: 600, BudgetCell: 1291, ExpiresUnix: 1790003600,
	}
	if fmt.Sprintf("%+v", c) != fmt.Sprintf("%+v", want) {
		t.Fatalf("golden v1 = %+v, want %+v", c, want)
	}
	if err := CheckModeConfig(ModeCanary, c); err != nil {
		t.Fatalf("golden v1 canary: %v", err)
	}
	if err := CheckSupported(ModeCanary, c); err != nil {
		t.Fatalf("golden v1 canary must stay bootable: %v", err)
	}
	// A different pin is still ErrConfigHash, before any decoding.
	other := pin
	other[0] ^= 1
	if _, err := ParseConfig(data, other); !errors.Is(err, ErrConfigHash) {
		t.Fatalf("pin mismatch: %v", err)
	}
	// json.Marshal of a v1 Config has exactly the HL1 members (cmd/qsdm
	// tests and tools marshal Config).
	b, err := json.Marshal(want)
	if err != nil || string(b) != `{"version":1,"allowed":[{"miner_addr":"`+strings.Repeat("0", 64)+
		`","node_id":"EXAMPLE-NODE-ID"}],"max_proofs_per_min":60,"max_proofs_total":3000,"max_pending":600,"budget_cell":1291,"expires_unix":1790003600}` {
		t.Fatalf("v1 marshal = %s, %v", b, err)
	}
}

// A v1 file is decoded against the HL1 field set only: every v2 field is an
// unknown field in a v1 file.
func TestConfigV1RejectsV2Fields(t *testing.T) {
	for _, f := range []string{
		`"max_proofs_per_min_per_owner":10`, `"max_pending_per_owner":100`, `"owner_epoch_cap_cell":100`,
		`"difficulty_bits":20`, `"require_operator_sig":true`, `"require_operator_sig":false`,
		`"require_fully_bonded":true`, `"bonded_slot_cap":1`, `"deferred_slot_weight_permille":0`,
		`"deferred_slot_weight_permille":100`,
	} {
		doc := strings.Replace(goldenPhase1, `"version": 1,`, `"version": 1, `+f+`,`, 1)
		_, err := ParseConfig([]byte(doc), sha256.Sum256([]byte(doc)))
		if !errors.Is(err, ErrConfig) || !strings.Contains(err.Error(), "unknown field") {
			t.Errorf("v1 with %s: %v, want unknown field", f, err)
		}
	}
	// A v1 Config built in code with a v2 field set is invalid too.
	c := gtConfig()
	c.DifficultyBits = 20
	if err := ValidateConfig(c); !errors.Is(err, ErrConfig) || !strings.Contains(err.Error(), "version 2 field") {
		t.Errorf("v1 Config with difficulty_bits: %v", err)
	}
	c = gtConfig()
	c.RequireOperatorSig = true
	if err := ValidateConfig(c); !errors.Is(err, ErrConfig) {
		t.Errorf("v1 Config with require_operator_sig: %v", err)
	}
	c = gtConfig()
	c.DeferredSlotWeightPermille = 100
	if err := ValidateConfig(c); !errors.Is(err, ErrConfig) || !strings.Contains(err.Error(), "version 2 field") {
		t.Errorf("v1 Config with deferred_slot_weight_permille: %v", err)
	}
}

// v2Doc is a valid public v2 config with two allowed entries.
func v2Doc() string {
	return `{"version":2,
 "allowed":[{"miner_addr":"` + gtMiner + `","node_id":"` + gtNode + `"},{"miner_addr":"` + gtOther + `","node_id":"n2"}],
 "max_proofs_per_min":120,"max_proofs_per_min_per_owner":20,"max_proofs_total":72000,
 "max_pending":600,"max_pending_per_owner":100,"owner_epoch_cap_cell":5000,"difficulty_bits":24,
 "require_operator_sig":true,"require_fully_bonded":true,"bonded_slot_cap":4,
 "budget_cell":30808,"expires_unix":1790086400}
`
}

func v2Config() Config {
	return Config{
		Version:                 2,
		Allowed:                 []AllowEntry{{MinerAddr: gtMiner, NodeID: gtNode}, {MinerAddr: gtOther, NodeID: "n2"}},
		MaxProofsPerMin:         120,
		MaxProofsPerMinPerOwner: 20,
		MaxProofsTotal:          72000,
		MaxPending:              600,
		MaxPendingPerOwner:      100,
		OwnerEpochCapCell:       5000,
		DifficultyBits:          24,
		RequireOperatorSig:      true,
		RequireFullyBonded:      true,
		BondedSlotCap:           4,
		BudgetCell:              30808,
		ExpiresUnix:             1790086400,
	}
}

func TestConfigV2StrictDecode(t *testing.T) {
	good := v2Doc()
	c, err := ParseConfig([]byte(good), sha256.Sum256([]byte(good)))
	if err != nil {
		t.Fatalf("v2: %v", err)
	}
	if fmt.Sprintf("%+v", c) != fmt.Sprintf("%+v", v2Config()) {
		t.Fatalf("v2 = %+v\nwant %+v", c, v2Config())
	}
	if _, err := ParseConfig([]byte(good), sha256.Sum256([]byte("x"))); !errors.Is(err, ErrConfigHash) {
		t.Fatalf("v2 pin mismatch: %v", err)
	}
	edit := func(from, to string) string {
		if !strings.Contains(good, from) {
			t.Fatalf("fixture lacks %q", from)
		}
		return strings.Replace(good, from, to, 1)
	}
	for name, c := range map[string]struct{ doc, want string }{
		"unknown field":    {edit(`"version":2`, `"version":2,"extra":0`), "unknown field"},
		"unknown nested":   {edit(`"node_id":"n2"`, `"node_id":"n2","x":1`), "unknown field"},
		"trailing object":  {good + `{}`, "trailing data"},
		"trailing garbage": {good + `x`, "trailing data"},
		"bool as string":   {edit(`"require_operator_sig":true`, `"require_operator_sig":"true"`), "cannot unmarshal"},
		"fractional bits":  {edit(`"difficulty_bits":24`, `"difficulty_bits":24.5`), "cannot unmarshal"},
		"negative cap":     {edit(`"owner_epoch_cap_cell":5000`, `"owner_epoch_cap_cell":-1`), "cannot unmarshal"},
		"missing per-own":  {edit(`"max_proofs_per_min_per_owner":20,`, ``), "max_proofs_per_min_per_owner 0"},
		"missing bits":     {edit(`"difficulty_bits":24,`, ``), "difficulty_bits 0"},
		"fractional tier":  {edit(`"bonded_slot_cap":4,`, `"bonded_slot_cap":4,"deferred_slot_weight_permille":0.5,`), "cannot unmarshal"},
		"tier with bond":   {edit(`"bonded_slot_cap":4,`, `"bonded_slot_cap":4,"deferred_slot_weight_permille":100,`), "needs require_fully_bonded false"},
		"array":            {`[]`, "cannot unmarshal"},
	} {
		_, err := ParseConfig([]byte(c.doc), sha256.Sum256([]byte(c.doc)))
		if !errors.Is(err, ErrConfig) || !strings.Contains(err.Error(), c.want) {
			t.Errorf("%s: %v, want ErrConfig containing %q", name, err, c.want)
		}
	}
	// Absent booleans decode as false; absent allowed is an empty list.
	min := edit(`"require_operator_sig":true,"require_fully_bonded":true,`, ``)
	min = strings.Replace(min, `"allowed":[{"miner_addr":"`+gtMiner+`","node_id":"`+gtNode+`"},{"miner_addr":"`+gtOther+`","node_id":"n2"}],`, ``, 1)
	c2, err := ParseConfig([]byte(min), sha256.Sum256([]byte(min)))
	if err != nil || c2.RequireOperatorSig || c2.RequireFullyBonded || len(c2.Allowed) != 0 || c2.DeferredSlotWeightPermille != 0 {
		t.Fatalf("minimal v2: %+v, %v", c2, err)
	}
	// The deferred-bond tier field decodes (HL2 operator decision A).
	tier := edit(`"require_fully_bonded":true,"bonded_slot_cap":4,`, `"require_fully_bonded":false,"bonded_slot_cap":4,"deferred_slot_weight_permille":250,`)
	c3, err := ParseConfig([]byte(tier), sha256.Sum256([]byte(tier)))
	if err != nil || c3.DeferredSlotWeightPermille != 250 || c3.RequireFullyBonded {
		t.Fatalf("tier v2: %+v, %v", c3, err)
	}
}

// The v2 validation table: each case names the text its error must contain.
func TestValidateConfigV2(t *testing.T) {
	if err := ValidateConfig(v2Config()); err != nil {
		t.Fatalf("valid v2: %v", err)
	}
	many := make([]AllowEntry, MaxAllowedEntries+1)
	for i := range many {
		many[i] = AllowEntry{MinerAddr: gtMiner, NodeID: fmt.Sprintf("n%d", i)}
	}
	for name, c := range map[string]struct {
		mut  func(*Config)
		want string // "" means valid
	}{
		"no allowed":            {func(c *Config) { c.Allowed = nil }, ""},
		"K allowed":             {func(c *Config) { c.Allowed = many[:MaxAllowedEntries] }, ""},
		"K+1 allowed":           {func(c *Config) { c.Allowed = many }, "65 allowed entries"},
		"same owner two nodes":  {func(c *Config) { c.Allowed[1].MinerAddr = gtMiner }, ""},
		"duplicate node":        {func(c *Config) { c.Allowed[1].NodeID = gtNode }, "allowed[1].node_id repeats allowed[0]"},
		"bad miner":             {func(c *Config) { c.Allowed[1].MinerAddr = strings.ToUpper(gtOther) }, "allowed[1].miner_addr"},
		"empty node":            {func(c *Config) { c.Allowed[0].NodeID = "" }, "allowed[0].node_id is empty"},
		"zero per-min":          {func(c *Config) { c.MaxProofsPerMin = 0 }, "max_proofs_per_min 0 outside"},
		"per-min at limit":      {func(c *Config) { c.MaxProofsPerMin = MaxProofsPerMinLimit }, ""},
		"per-min over limit":    {func(c *Config) { c.MaxProofsPerMin = MaxProofsPerMinLimit + 1 }, "max_proofs_per_min 6001"},
		"zero per-owner rate":   {func(c *Config) { c.MaxProofsPerMinPerOwner = 0 }, "max_proofs_per_min_per_owner 0"},
		"per-owner = global":    {func(c *Config) { c.MaxProofsPerMinPerOwner = c.MaxProofsPerMin }, ""},
		"per-owner > global":    {func(c *Config) { c.MaxProofsPerMinPerOwner = c.MaxProofsPerMin + 1 }, "max_proofs_per_min_per_owner 121"},
		"zero total":            {func(c *Config) { c.MaxProofsTotal = 0 }, "max_proofs_total"},
		"zero pending":          {func(c *Config) { c.MaxPending = 0 }, "max_pending 0"},
		"pending over 1024":     {func(c *Config) { c.MaxPending = 1025; c.MaxPendingPerOwner = 1 }, "max_pending 1025"},
		"zero owner pending":    {func(c *Config) { c.MaxPendingPerOwner = 0 }, "max_pending_per_owner 0"},
		"owner pending = total": {func(c *Config) { c.MaxPendingPerOwner = c.MaxPending }, ""},
		"owner pending > total": {func(c *Config) { c.MaxPendingPerOwner = c.MaxPending + 1 }, "max_pending_per_owner 601"},
		"zero budget":           {func(c *Config) { c.BudgetCell = 0 }, "budget_cell must be > 0"},
		"zero epoch cap":        {func(c *Config) { c.OwnerEpochCapCell = 0 }, "owner_epoch_cap_cell 0"},
		"epoch cap = budget":    {func(c *Config) { c.OwnerEpochCapCell = c.BudgetCell }, ""},
		"epoch cap > budget":    {func(c *Config) { c.OwnerEpochCapCell = c.BudgetCell + 1 }, "owner_epoch_cap_cell 30809"},
		"bits 15":               {func(c *Config) { c.DifficultyBits = 15 }, "difficulty_bits 15 outside 16..48"},
		"bits 16":               {func(c *Config) { c.DifficultyBits = MinDifficultyBits }, ""},
		"bits 48":               {func(c *Config) { c.DifficultyBits = MaxDifficultyBits }, ""},
		"bits 49":               {func(c *Config) { c.DifficultyBits = 49 }, "difficulty_bits 49"},
		"zero slot cap":         {func(c *Config) { c.BondedSlotCap = 0 }, "bonded_slot_cap 0 outside 1..64"},
		"slot cap 64":           {func(c *Config) { c.BondedSlotCap = MaxBondedSlotCap }, ""},
		"slot cap 65":           {func(c *Config) { c.BondedSlotCap = 65 }, "bonded_slot_cap 65"},
		"zero expiry":           {func(c *Config) { c.ExpiresUnix = 0 }, "expires_unix must be > 0"},
		"expired loads":         {func(c *Config) { c.ExpiresUnix = 1 }, ""},
		"no sig, no bond":       {func(c *Config) { c.RequireOperatorSig, c.RequireFullyBonded = false, false }, ""},
		"tier 1":                {func(c *Config) { c.RequireFullyBonded, c.DeferredSlotWeightPermille = false, 1 }, ""},
		"tier 1000":             {func(c *Config) { c.RequireFullyBonded, c.DeferredSlotWeightPermille = false, SlotUnit }, ""},
		"tier 1001":             {func(c *Config) { c.RequireFullyBonded, c.DeferredSlotWeightPermille = false, 1001 }, "deferred_slot_weight_permille 1001 outside 0..1000"},
		"tier negative":         {func(c *Config) { c.RequireFullyBonded, c.DeferredSlotWeightPermille = false, -1 }, "deferred_slot_weight_permille -1"},
		"tier with full bond":   {func(c *Config) { c.DeferredSlotWeightPermille = 100 }, "needs require_fully_bonded false"},
		"version 3":             {func(c *Config) { c.Version = 3 }, "version 3, want 1 or 2"},
	} {
		cfg := v2Config()
		c.mut(&cfg)
		err := ValidateConfig(cfg)
		if c.want == "" {
			if err != nil {
				t.Errorf("%s: %v, want valid", name, err)
			}
			continue
		}
		if !errors.Is(err, ErrConfig) || !strings.Contains(err.Error(), c.want) {
			t.Errorf("%s: %v, want ErrConfig containing %q", name, err, c.want)
		}
	}
	// Every violated rule is listed.
	cfg := v2Config()
	cfg.DifficultyBits, cfg.BondedSlotCap = 0, 0
	if err := ValidateConfig(cfg); err == nil || !strings.Contains(err.Error(), "difficulty_bits") || !strings.Contains(err.Error(), "bonded_slot_cap") {
		t.Errorf("two violations: %v", err)
	}
}

// The mode/version matrix (CheckModeConfig) and the S2 gate
// (CheckSupported). Since WP-E canary v1, canary v2 and public v2 with
// require_operator_sig boot.
func TestModeVersionMatrix(t *testing.T) {
	v1 := gtConfig()
	v2 := v2Config()
	v2NoSig := v2Config()
	v2NoSig.RequireOperatorSig = false
	v2NoBond := v2Config()
	v2NoBond.RequireFullyBonded = false
	v2Open := v2Config()
	v2Open.Allowed = nil
	v2CanaryNoReq := v2Config()
	v2CanaryNoReq.RequireOperatorSig, v2CanaryNoReq.RequireFullyBonded = false, false
	invalid := gtConfig()
	invalid.MaxPending = 0
	v2Tier := v2Config()
	v2Tier.RequireFullyBonded, v2Tier.DeferredSlotWeightPermille = false, 100
	v2TierNoSig := v2Tier
	v2TierNoSig.RequireOperatorSig = false

	type want struct{ mode, supported error }
	for _, c := range []struct {
		name string
		mode Mode
		cfg  Config
		want want
	}{
		{"canary v1", ModeCanary, v1, want{nil, nil}},
		{"canary v2", ModeCanary, v2, want{nil, nil}},
		{"canary v2 without sig/bond", ModeCanary, v2CanaryNoReq, want{nil, nil}},
		{"canary v2 empty allowlist", ModeCanary, v2Open, want{ErrConfig, nil}},
		{"canary v2 tier", ModeCanary, v2Tier, want{nil, nil}},
		{"canary invalid v1", ModeCanary, invalid, want{ErrConfig, nil}},
		{"public v2", ModePublic, v2, want{nil, nil}},
		{"public v2 no allowlist", ModePublic, v2Open, want{nil, nil}},
		{"public v2 deferred tier", ModePublic, v2Tier, want{nil, nil}},
		{"public v1", ModePublic, v1, want{ErrConfig, ErrNotImplemented}},
		{"public v2 no operator sig", ModePublic, v2NoSig, want{ErrConfig, ErrNotImplemented}},
		{"public v2 tier no operator sig", ModePublic, v2TierNoSig, want{ErrConfig, ErrNotImplemented}},
		{"public v2 not fully bonded", ModePublic, v2NoBond, want{ErrConfig, nil}},
		{"off v1", ModeOff, v1, want{ErrConfig, nil}},
		{"unknown v2", Mode("open"), v2, want{ErrConfig, ErrNotImplemented}},
		{"canary version 3", ModeCanary, Config{Version: 3}, want{ErrConfig, ErrNotImplemented}},
	} {
		err := CheckModeConfig(c.mode, c.cfg)
		if (c.want.mode == nil) != (err == nil) || (c.want.mode != nil && !errors.Is(err, c.want.mode)) {
			t.Errorf("%s: CheckModeConfig = %v, want %v", c.name, err, c.want.mode)
		}
		err = CheckSupported(c.mode, c.cfg)
		if (c.want.supported == nil) != (err == nil) || (c.want.supported != nil && !errors.Is(err, c.want.supported)) {
			t.Errorf("%s: CheckSupported = %v, want %v", c.name, err, c.want.supported)
		}
	}
	err := CheckSupported(ModePublic, v2NoSig)
	if err == nil || !strings.Contains(err.Error(), "not yet implemented") || !strings.Contains(err.Error(), "require_operator_sig") {
		t.Errorf("unsigned public refusal must say why: %v", err)
	}
	if err := CheckModeConfig(ModePublic, v2NoSig); err == nil || !strings.Contains(err.Error(), "require_operator_sig must be true") {
		t.Errorf("public without operator sig: %v", err)
	}
	if err := CheckModeConfig(ModePublic, v2NoBond); err == nil || !strings.Contains(err.Error(), "require_fully_bonded must be true unless deferred_slot_weight_permille is set") {
		t.Errorf("public not fully bonded without the tier: %v", err)
	}
	if err := CheckModeConfig(ModePublic, v1); err == nil || !strings.Contains(err.Error(), "version 1, want 2") {
		t.Errorf("public v1: %v", err)
	}
}

// NewGuard refuses a valid v2 config with require_operator_sig until an
// OwnerAuth exists (WP-C), instead of silently ignoring the field. WP-B's
// v2 guard options are tested in guard_owner_test.go.
func TestNewGuardRefusesV2(t *testing.T) {
	_, err := NewGuard(GuardOptions{
		Dir: gtDir(t), Config: v2Config(), FailStop: func(int, string) {},
		EnrollmentActive: func(string, string) bool { return true },
	})
	if !errors.Is(err, ErrNotImplemented) {
		t.Fatalf("NewGuard(v2) = %v, want ErrNotImplemented", err)
	}
}

// The committed v2 example (hl1/canary) is generator output and passes the
// production decoder and the public mode rules.
func TestConfigV2Example(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "hl1", "canary", "mining-public.v2.example.json"))
	if err != nil {
		t.Fatal(err)
	}
	c, err := ParseConfig(data, sha256.Sum256(data))
	if err != nil {
		t.Fatalf("v2 example: %v", err)
	}
	if err := CheckModeConfig(ModePublic, c); err != nil {
		t.Fatalf("v2 example, public: %v", err)
	}
	if err := CheckSupported(ModePublic, c); err != nil {
		t.Fatalf("v2 example must be bootable since WP-E: %v", err)
	}
	if d := ConfigDifficulty(c); d == nil || d.BitLen()-1 != c.DifficultyBits {
		t.Fatalf("v2 example difficulty %v, bits %d", d, c.DifficultyBits)
	}
}
